(function(){'use strict';const hamburger=document.getElementById('fullscreenHamburger');const overlay=document.getElementById('fullscreenNavOverlay');const closeBtn=document.getElementById('fullscreenCloseBtn');let backdrop=document.getElementById('fullscreenNavBackdrop');if(!backdrop){backdrop=document.createElement('div');backdrop.id='fullscreenNavBackdrop';backdrop.className='fullscreen-nav-backdrop';if(overlay&&overlay.parentNode){overlay.parentNode.insertBefore(backdrop,overlay)}else{document.body.appendChild(backdrop)}}
if(!hamburger||!overlay)return;function isMobileLayout(){return window.matchMedia('(max-width: 767px)').matches}
function openMenu(){backdrop.classList.add('is-visible');overlay.classList.add('is-open');overlay.setAttribute('aria-hidden','false');hamburger.classList.add('is-active');hamburger.setAttribute('aria-expanded','true');document.body.style.overflow=isMobileLayout()?'':'hidden';const firstLink=overlay.querySelector('a, button');if(firstLink)firstLink.focus()}
function closeMenu(){backdrop.classList.remove('is-visible');overlay.classList.remove('is-open');overlay.setAttribute('aria-hidden','true');hamburger.classList.remove('is-active');hamburger.setAttribute('aria-expanded','false');document.body.style.overflow='';overlay.querySelectorAll('.nav-sub').forEach(function(sub){sub.classList.remove('is-visible')});overlay.querySelectorAll('.fullscreen-nav-main > li').forEach(function(item){item.classList.remove('submenu-open')});overlay.querySelectorAll('.has-sub').forEach(function(link){link.classList.remove('sub-is-open');link.setAttribute('aria-expanded','false')});hamburger.focus()}
hamburger.addEventListener('click',openMenu);if(closeBtn){closeBtn.addEventListener('click',closeMenu)}
backdrop.addEventListener('click',closeMenu);const navInner=overlay.querySelector('.fullscreen-nav-inner');if(navInner){navInner.addEventListener('click',function(e){if(!e.target.closest('a, button')){closeMenu()}})}
document.addEventListener('keydown',function(e){if(e.key==='Escape'&&overlay.classList.contains('is-open')){closeMenu()}});overlay.querySelectorAll('.has-sub').forEach(function(link){var subId=link.getAttribute('data-sub');var parentItem=link.closest('li');var sub=parentItem?parentItem.querySelector('.nav-sub'):null;if(!sub&&subId){sub=document.getElementById(subId)}
if(!sub)return;var hideTimer=null;function showSub(){clearTimeout(hideTimer);link.classList.add('sub-is-open');link.setAttribute('aria-expanded','true');if(parentItem)parentItem.classList.add('submenu-open');sub.classList.add('is-visible')}
function scheduleHide(){hideTimer=setTimeout(function(){link.classList.remove('sub-is-open');link.setAttribute('aria-expanded','false');sub.classList.remove('is-visible');if(parentItem)parentItem.classList.remove('submenu-open')},120)}
link.addEventListener('mouseenter',function(){if(isMobileLayout())return;showSub()});link.addEventListener('mouseleave',function(){if(isMobileLayout())return;scheduleHide()});sub.addEventListener('mouseenter',function(){if(isMobileLayout())return;clearTimeout(hideTimer)});sub.addEventListener('mouseleave',function(){if(isMobileLayout())return;scheduleHide()});link.addEventListener('click',function(e){if(!isMobileLayout())return;if(!sub.classList.contains('is-visible')){e.preventDefault();overlay.querySelectorAll('.has-sub.sub-is-open').forEach(function(openLink){if(openLink===link)return;openLink.classList.remove('sub-is-open');openLink.setAttribute('aria-expanded','false');var openParent=openLink.closest('li');if(openParent){openParent.classList.remove('submenu-open');var openSub=openParent.querySelector('.nav-sub');if(openSub)openSub.classList.remove('is-visible')}});showSub()}});link.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();if(sub.classList.contains('is-visible')){scheduleHide()}else{showSub();var firstSubLink=sub.querySelector('a');if(firstSubLink)firstSubLink.focus()}}})});overlay.addEventListener('keydown',function(e){if(e.key!=='Tab')return;if(!overlay.classList.contains('is-open'))return;var focusable=Array.from(overlay.querySelectorAll('a[href], button:not([disabled]), [tabindex]:not([tabindex="-1"])')).filter(function(el){return!el.closest('.nav-sub:not(.is-visible)')});if(focusable.length===0)return;var first=focusable[0];var last=focusable[focusable.length-1];if(e.shiftKey){if(document.activeElement===first){e.preventDefault();last.focus()}}else{if(document.activeElement===last){e.preventDefault();first.focus()}}})})()